/**:
  ros__parameters:
    # Joystick Teleop Settings
    deadzone: 0.2

    # Headlight Control
    headlight_up_button: 0
    headlight_down_button: 1
    headlight_step: 64.0

    # Controller axis mappings
    linear_axis: 1
    angular_axis: 3